### ISSUE TITLE
Update symbols with latest values

### ISSUE THREAD

**Issue by rmorrin** [rmorrin/FixerSharp#12]
Fixer has updated its list of supported currencies, and as a result the `Symbols` constants is now missing a large number of values.

Full list of supported symbols can be found at http://data.fixer.io/api/symbols?access_key=API_KEY

**Comment by malcolmhue** [comment]
Voting this one up. Almost all the African currencies are missing (eg: MZN, ZMW, etcetera). Would be great to get them added.

**Comment by naveddeshmukh** [comment]
😃

**Comment by malcolmhue** [comment]
Thank you.
