### ISSUE TITLE
.NET Standard support

### ISSUE THREAD

**Issue by ffMathy** [rmorrin/FixerSharp#5]
The package should be recompiled to .NET Standard.

**Comment by rmorrin** [comment]
Hello! This is in the works, I've migrated the library across to target .NET Standard 1.1 and ported some of the code using unavailable APIs. I'll try to get this pushed up asap.

Thanks for the contribution! 👍

**Comment by rmorrin** [comment]
Version 1.2.0 of the library now targets .NET Standard 1.1! 😄

**Comment by ffMathy** [comment]
Awesome! Thanks!
