### ISSUE TITLE
Fixer.io new endpoint

### ISSUE THREAD

**Issue by mapuglisi** [rmorrin/FixerSharp#8]
Fixer.io changed their API endpoint, making all tests of this code return a 404 not found response message.

**Comment by mypalchris** [comment]
This has been of great use to me - thanks. Will it be updated?

**Comment by ProNotion** [comment]
There is a pull-request from @mapuglisi that should be merged and released ASAP as this library is now dead without the updated API endpoint. #9

**Comment by ProNotion** [comment]
@Maestro85282 You could do what I did and download and build it with the correct endpoint as I have had to do for now. It would be good though to see this updated in the official release.

**Comment by Maestro85282** [comment]
@ProNotion  yea, good advice, will do that.  thanks

**Comment by Maestro85282** [comment]
@ProNotion hey, did you have to modify your Fixer.ParseData method?  I get an error on the rates.Add line in Fixer.ParseData... "**Can not add property EUR to Newtonsoft.Json.Linq.JObject. Property with the same name already exists on object.**"   

I am calling ExchangeRate rate = Fixer.Rate("AUD", "USD", null);

Thanks

**Comment by mapuglisi** [comment]
@Maestro85282 That is because in the old version Fixer wouldn't give you EUR conversion and now they do, so there is no need of adding EUR at the list in `ExchangeRate ParseData`... Deleting `rates.Add(baseSymbol, 1.00);` should be enough...

You can check the changes I did on the pull request.

**Comment by rmorrin** [comment]
Apologies for the delay with this, will work with @mapuglisi to get PR merged and put out an update ASAP 😃

**Comment by rmorrin** [comment]
Quick update on this - I've got a working version of the library on the [new-api-compatibility](https://github.com/rmorrin/FixerSharp/commits/new-api-compatibility) branch. Just waiting for a response on from @mapuglisi on #9 to give him the opportunity to update his PR. If I don't hear back by later on this week, I will merge this branch and get a working version published to NuGet.

**Comment by rmorrin** [comment]
Fixed by #10
